-- Generated by the database client.
CREATE TABLE admin(
    admin_id SERIAL NOT NULL,
    user_id integer NOT NULL,
    fullname varchar(100),
    position varchar(50),
    gender gender_enum,
    mobile_number varchar(20),
    email varchar(100),
    PRIMARY KEY(admin_id),
    CONSTRAINT admin_user_id_fkey FOREIGN key(user_id) REFERENCES users(user_id)
);
CREATE UNIQUE INDEX admin_user_id_key ON public.admin USING btree (user_id);
CREATE UNIQUE INDEX admin_email_key ON public.admin USING btree (email);


-- Generated by the database client.
CREATE TABLE announcement_officer_recipients(
    announcement_id integer NOT NULL,
    officer_id integer NOT NULL,
    PRIMARY KEY(announcement_id,officer_id),
    CONSTRAINT announcement_officer_recipients_announcement_id_fkey FOREIGN key(announcement_id) REFERENCES announcements(announcement_id),
    CONSTRAINT announcement_officer_recipients_officer_id_fkey FOREIGN key(officer_id) REFERENCES officers(officer_id)
);
CREATE INDEX idx_announcement_officer_recipients_officer_id ON public.announcement_officer_recipients USING btree (officer_id);

-- Generated by the database client.
CREATE TABLE announcement_recipients(
    announcement_id integer NOT NULL,
    coop_id integer NOT NULL,
    PRIMARY KEY(announcement_id,coop_id),
    CONSTRAINT announcement_recipients_announcement_id_fkey FOREIGN key(announcement_id) REFERENCES announcements(announcement_id),
    CONSTRAINT announcement_recipients_coop_id_fkey FOREIGN key(coop_id) REFERENCES cooperatives(coop_id)
);

-- Generated by the database client.
CREATE TABLE announcements(
    announcement_id SERIAL NOT NULL,
    staff_id integer,
    admin_id integer,
    description text,
    "type" announcement_type_enum,
    attachment bytea,
    sent_at timestamp with time zone,
    scope varchar(50),
    title varchar(200),
    status_classification announcement_status_enum NOT NULL DEFAULT 'draft'::announcement_status_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(announcement_id),
    CONSTRAINT announcements_staff_id_fkey FOREIGN key(staff_id) REFERENCES staff(staff_id),
    CONSTRAINT announcements_admin_id_fkey FOREIGN key(admin_id) REFERENCES admin(admin_id),
    CONSTRAINT announcement_sender_check CHECK (((staff_id IS NOT NULL) AND (admin_id IS NULL)) OR ((staff_id IS NULL) AND (admin_id IS NOT NULL)))
);

-- Generated by the database client.
CREATE TABLE auth_group(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    name varchar(150) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX auth_group_name_key ON public.auth_group USING btree (name);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- Generated by the database client.
CREATE TABLE auth_group_permissions(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN key(group_id) REFERENCES auth_group(id),
    CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN key(permission_id) REFERENCES auth_permission(id)
);
CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON public.auth_group_permissions USING btree (group_id, permission_id);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

-- Generated by the database client.
CREATE TABLE auth_permission(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    name varchar(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename varchar(100) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN key(content_type_id) REFERENCES django_content_type(id)
);
CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON public.auth_permission USING btree (content_type_id, codename);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

-- Generated by the database client.
CREATE TABLE auth_user(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    password varchar(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username varchar(150) NOT NULL,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    email varchar(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX auth_user_username_key ON public.auth_user USING btree (username);
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);

-- Generated by the database client.
CREATE TABLE auth_user_groups(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN key(user_id) REFERENCES auth_user(id),
    CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN key(group_id) REFERENCES auth_group(id)
);
CREATE UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq ON public.auth_user_groups USING btree (user_id, group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);

-- Generated by the database client.
CREATE TABLE auth_user_user_permissions(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN key(user_id) REFERENCES auth_user(id),
    CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN key(permission_id) REFERENCES auth_permission(id)
);
CREATE UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq ON public.auth_user_user_permissions USING btree (user_id, permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);

-- Generated by the database client.
-- Generated by the database client.
CREATE TABLE cooperatives(
    coop_id SERIAL NOT NULL,
    staff_id integer,
    cooperative_name varchar(200) NOT NULL,
    mobile_number varchar(20),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(coop_id),
    CONSTRAINT cooperatives_staff_id_fkey FOREIGN key(staff_id) REFERENCES staff(staff_id)
);
CREATE UNIQUE INDEX cooperatives_cooperative_name_key ON public.cooperatives USING btree (cooperative_name);

-- Generated by the database client.
CREATE TABLE django_admin_log(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr varchar(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN key(content_type_id) REFERENCES django_content_type(id),
    CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN key(user_id) REFERENCES auth_user(id),
    CONSTRAINT django_admin_log_action_flag_check CHECK (action_flag >= 0)
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

-- Generated by the database client.
CREATE TABLE django_content_type(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON public.django_content_type USING btree (app_label, model);

-- Generated by the database client.
CREATE TABLE django_migrations(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamp with time zone NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE django_session(
    session_key varchar(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    PRIMARY KEY(session_key)
);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

-- Generated by the database client.
CREATE TABLE financial_data(
    financial_id SERIAL NOT NULL,
    coop_id integer NOT NULL,
    assets numeric(20,2) DEFAULT 0,
    paid_up_capital numeric(20,2) DEFAULT 0,
    net_surplus numeric(20,2) DEFAULT 0,
    attachments bytea,
    approval_status approval_status_enum,
    report_year integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(financial_id),
    CONSTRAINT financial_data_coop_id_fkey FOREIGN key(coop_id) REFERENCES cooperatives(coop_id),
    CONSTRAINT financial_data_report_year_check CHECK ((report_year >= 1900) AND ((report_year)::numeric <= (EXTRACT(year FROM now()) + (1)::numeric)))
);
CREATE INDEX idx_financial_coop_id ON public.financial_data USING btree (coop_id);

-- Generated by the database client.
CREATE TABLE members(
    member_id SERIAL NOT NULL,
    coop_id integer NOT NULL,
    fullname varchar(100) NOT NULL,
    gender gender_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(member_id),
    CONSTRAINT members_coop_id_fkey FOREIGN key(coop_id) REFERENCES cooperatives(coop_id)
);
CREATE INDEX idx_members_coop_id ON public.members USING btree (coop_id);

-- Generated by the database client.
CREATE TABLE message_recipients(
    message_id integer NOT NULL,
    receiver_id integer NOT NULL,
    received_at timestamp with time zone,
    PRIMARY KEY(message_id,receiver_id),
    CONSTRAINT message_recipients_message_id_fkey FOREIGN key(message_id) REFERENCES messages(message_id),
    CONSTRAINT message_recipients_receiver_id_fkey FOREIGN key(receiver_id) REFERENCES users(user_id)
);

-- Generated by the database client.
CREATE TABLE messages(
    message_id SERIAL NOT NULL,
    sender_id integer,
    message text NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(message_id),
    CONSTRAINT messages_sender_id_fkey FOREIGN key(sender_id) REFERENCES users(user_id)
);

-- Generated by the database client.
CREATE TABLE officers(
    officer_id SERIAL NOT NULL,
    user_id integer,
    coop_id integer NOT NULL,
    fullname varchar(100),
    position varchar(50),
    gender gender_enum,
    mobile_number varchar(20),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    email varchar(100),
    PRIMARY KEY(officer_id),
    CONSTRAINT officers_user_id_fkey FOREIGN key(user_id) REFERENCES users(user_id),
    CONSTRAINT officers_coop_id_fkey FOREIGN key(coop_id) REFERENCES cooperatives(coop_id)
);
CREATE INDEX idx_officers_coop_id ON public.officers USING btree (coop_id);

-- Generated by the database client.
CREATE TABLE profile_data(
    profile_id SERIAL NOT NULL,
    coop_id integer NOT NULL,
    address varchar(255),
    mobile_number varchar(20),
    email_address varchar(100),
    cda_registration_number varchar(100),
    cda_registration_date date,
    lccdc_membership boolean,
    lccdc_membership_date date,
    operation_area varchar(100),
    business_activity varchar(100),
    board_of_directors_count integer,
    salaried_employees_count integer,
    coc_renewal boolean,
    cote_renewal boolean,
    coc_attachment bytea,
    cote_attachment bytea,
    approval_status approval_status_enum,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(profile_id),
    CONSTRAINT profile_data_coop_id_fkey FOREIGN key(coop_id) REFERENCES cooperatives(coop_id)
);
CREATE UNIQUE INDEX profile_data_coop_id_key ON public.profile_data USING btree (coop_id);
CREATE INDEX idx_profile_coop_id ON public.profile_data USING btree (coop_id);

-- Generated by the database client.
CREATE TABLE staff(
    staff_id SERIAL NOT NULL,
    user_id integer NOT NULL,
    fullname varchar(100),
    position varchar(50),
    gender gender_enum,
    mobile_number varchar(20),
    email varchar(100),
    PRIMARY KEY(staff_id),
    CONSTRAINT staff_user_id_fkey FOREIGN key(user_id) REFERENCES users(user_id)
);
CREATE UNIQUE INDEX staff_user_id_key ON public.staff USING btree (user_id);
CREATE UNIQUE INDEX staff_email_key ON public.staff USING btree (email);

-- Generated by the database client.
CREATE TABLE users(
    user_id SERIAL NOT NULL,
    username varchar(50) NOT NULL,
    password_hash varchar(128) NOT NULL,
    role user_role_enum NOT NULL,
    verification_status verification_status_enum DEFAULT 'pending'::verification_status_enum,
    is_first_login boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY(user_id)
);
CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);