# Generated by Django 5.2.8 on 2025-11-28 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('coop_id', models.AutoField(primary_key=True, serialize=False)),
                ('cooperative_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('cda_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cda_registration_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_up_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('members_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cooperatives',
            },
        ),
        migrations.CreateModel(
            name='CooperativeOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'cooperative_officers',
            },
        ),
    ]
