# Generated by Django 5.2.7 on 2025-12-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '__first__'),
        ('cooperatives', '0001_initial'),
        ('users', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user_fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_management.cooperatives')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('financial_id', models.AutoField(primary_key=True, serialize=False)),
                ('assets', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_up_capital', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('attachments', models.BinaryField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('report_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management.cooperatives')),
            ],
            options={
                'db_table': 'financial_data',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management.cooperatives')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_year', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('cda_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cda_registration_date', models.DateField(blank=True, null=True)),
                ('lccdc_membership', models.BooleanField(blank=True, null=True)),
                ('lccdc_membership_date', models.DateField(blank=True, null=True)),
                ('operation_area', models.CharField(blank=True, max_length=100, null=True)),
                ('business_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('board_of_directors_count', models.IntegerField(blank=True, null=True)),
                ('salaried_employees_count', models.IntegerField(blank=True, null=True)),
                ('coc_renewal', models.BooleanField(blank=True, null=True)),
                ('cote_renewal', models.BooleanField(blank=True, null=True)),
                ('coc_attachment', models.BinaryField(blank=True, null=True)),
                ('cote_attachment', models.BinaryField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_management.cooperatives')),
            ],
            options={
                'db_table': 'profile_data',
                'unique_together': {('coop', 'report_year')},
            },
        ),
    ]
