# Generated by Django 5.2.8 on 2025-11-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativeofficer',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='cooperativeofficer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cooperative',
        ),
        migrations.DeleteModel(
            name='CooperativeOfficer',
        ),
    ]
